name: Cuisino
favicon: null
layout_spectrum: 0.22001014999113977
typography_spectrum: 0.23649599077180028
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.552239784039557
  lightness: 0.9799931612797081
  saturation: 0.3370788067113608
  rhythmicContrast: 0.49215404922142625
purpose: []
